# permissions for end users to view hexrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hexrolebinding-viewer-role
rules:
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings/status
  verbs:
  - get
