# permissions for end users to view hexroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hexrole-viewer-role
rules:
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexroles/status
  verbs:
  - get
