# permissions for end users to edit hexrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hexrolebinding-editor-role
rules:
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings/status
  verbs:
  - get
