
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings/finalizers
  verbs:
  - update
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexrolebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexroles/finalizers
  verbs:
  - update
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - hexroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - rocketbelt.hextech.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
